from datetime import date, datetime
from typing import Optional
from sqlalchemy import BigInteger, Integer, String, Boolean, Date, DateTime, Text, ForeignKey, Numeric, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base, TimestampMixin

class ComercialPipelineStage(Base):
    __tablename__='comercial_pipeline_stage'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); codigo:Mapped[str]=mapped_column(String(50),unique=True); nome:Mapped[str]=mapped_column(String(100)); ordem:Mapped[int]=mapped_column(Integer,default=0); ativo:Mapped[bool]=mapped_column(Boolean,default=True); tipo:Mapped[str]=mapped_column(String(30),default='aberto')
class ComercialLead(Base,TimestampMixin):
    __tablename__='comercial_lead'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); data_entrada:Mapped[date]=mapped_column(Date,default=date.today); nome_estabelecimento:Mapped[str]=mapped_column(String(180)); nome_fantasia:Mapped[Optional[str]]=mapped_column(String(180)); segmento:Mapped[Optional[str]]=mapped_column(String(80)); subsegmento:Mapped[Optional[str]]=mapped_column(String(80)); cidade:Mapped[Optional[str]]=mapped_column(String(100)); estado:Mapped[Optional[str]]=mapped_column(String(40)); bairro:Mapped[Optional[str]]=mapped_column(String(100)); telefone:Mapped[Optional[str]]=mapped_column(String(40)); whatsapp:Mapped[Optional[str]]=mapped_column(String(40)); email:Mapped[Optional[str]]=mapped_column(String(180)); origem:Mapped[Optional[str]]=mapped_column(String(80)); status_codigo:Mapped[str]=mapped_column(String(50),default='novo'); responsavel_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL')); observacoes:Mapped[Optional[str]]=mapped_column(Text); fit_score:Mapped[int]=mapped_column(Integer,default=0); opportunity_score:Mapped[int]=mapped_column(Integer,default=0); engagement_score:Mapped[int]=mapped_column(Integer,default=0); score_total:Mapped[int]=mapped_column(Integer,default=0); temperatura:Mapped[str]=mapped_column(String(20),default='frio'); ultimo_contato_em:Mapped[Optional[datetime]]=mapped_column(DateTime(timezone=True)); proxima_acao:Mapped[Optional[str]]=mapped_column(String(300)); proxima_acao_em:Mapped[Optional[datetime]]=mapped_column(DateTime(timezone=True)); nao_prospectar:Mapped[bool]=mapped_column(Boolean,default=False); tenant_id:Mapped[Optional[int]]=mapped_column(BigInteger,default=1); deleted_at:Mapped[Optional[datetime]]=mapped_column(DateTime(timezone=True))
class ComercialLeadContact(Base,TimestampMixin):
    __tablename__='comercial_lead_contact'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); nome:Mapped[str]=mapped_column(String(160)); cargo:Mapped[Optional[str]]=mapped_column(String(100)); telefone:Mapped[Optional[str]]=mapped_column(String(40)); whatsapp:Mapped[Optional[str]]=mapped_column(String(40)); email:Mapped[Optional[str]]=mapped_column(String(180)); principal:Mapped[bool]=mapped_column(Boolean,default=False)
class ComercialLeadChannel(Base,TimestampMixin):
    __tablename__='comercial_lead_channel'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); tipo:Mapped[str]=mapped_column(String(40)); valor:Mapped[str]=mapped_column(String(1000)); ativo:Mapped[bool]=mapped_column(Boolean,default=True)
class ComercialAudit(Base,TimestampMixin):
    __tablename__='comercial_audit'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); executado_por_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL')); resumo:Mapped[Optional[str]]=mapped_column(Text); tese_central:Mapped[Optional[str]]=mapped_column(Text); forcas:Mapped[list]=mapped_column(JSONB,default=list); vazamentos:Mapped[list]=mapped_column(JSONB,default=list); oportunidades:Mapped[list]=mapped_column(JSONB,default=list); prioridade:Mapped[Optional[str]]=mapped_column(String(80)); risco_comercial:Mapped[Optional[str]]=mapped_column(String(80)); observacoes:Mapped[list]=mapped_column(JSONB,default=list); modelo:Mapped[Optional[str]]=mapped_column(String(80))
class ComercialAuditSource(Base,TimestampMixin):
    __tablename__='comercial_audit_source'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); audit_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('comercial_audit.id',ondelete='SET NULL')); tipo:Mapped[str]=mapped_column(String(50)); fonte:Mapped[Optional[str]]=mapped_column(String(120)); url:Mapped[Optional[str]]=mapped_column(String(1200)); evidencia:Mapped[str]=mapped_column(Text); consultado_em:Mapped[datetime]=mapped_column(DateTime(timezone=True))
class ComercialInsight(Base,TimestampMixin):
    __tablename__='comercial_insight'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); audit_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('comercial_audit.id',ondelete='CASCADE')); categoria:Mapped[Optional[str]]=mapped_column(String(50)); titulo:Mapped[str]=mapped_column(String(220)); evidencia:Mapped[str]=mapped_column(Text); impacto:Mapped[str]=mapped_column(Text); fonte:Mapped[Optional[str]]=mapped_column(String(400)); grau_confianca:Mapped[str]=mapped_column(String(30),default='medio'); utilizado:Mapped[bool]=mapped_column(Boolean,default=False); utilizado_em:Mapped[Optional[datetime]]=mapped_column(DateTime(timezone=True)); ativo:Mapped[bool]=mapped_column(Boolean,default=True)
class ComercialMessage(Base,TimestampMixin):
    __tablename__='comercial_message'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); direcao:Mapped[str]=mapped_column(String(20)); canal:Mapped[str]=mapped_column(String(30)); tipo:Mapped[str]=mapped_column(String(40)); conteudo:Mapped[str]=mapped_column(Text); responsavel_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL')); insight_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('comercial_insight.id',ondelete='SET NULL')); status_antes:Mapped[Optional[str]]=mapped_column(String(50)); status_depois:Mapped[Optional[str]]=mapped_column(String(50)); enviado_em:Mapped[datetime]=mapped_column(DateTime(timezone=True)); metadados:Mapped[Optional[dict]]=mapped_column(JSONB)
class ComercialActivity(Base):
    __tablename__='comercial_activity'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); usuario_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL')); tipo:Mapped[str]=mapped_column(String(60)); descricao:Mapped[str]=mapped_column(Text); dados:Mapped[Optional[dict]]=mapped_column(JSONB); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ComercialTask(Base,TimestampMixin):
    __tablename__='comercial_task'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); titulo:Mapped[str]=mapped_column(String(220)); descricao:Mapped[Optional[str]]=mapped_column(Text); responsavel_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL')); prazo:Mapped[Optional[datetime]]=mapped_column(DateTime(timezone=True)); status:Mapped[str]=mapped_column(String(30),default='pendente')
class ComercialCadence(Base,TimestampMixin):
    __tablename__='comercial_cadence'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); nome:Mapped[str]=mapped_column(String(160)); descricao:Mapped[Optional[str]]=mapped_column(Text); ativa:Mapped[bool]=mapped_column(Boolean,default=True)
class ComercialCadenceStep(Base):
    __tablename__='comercial_cadence_step'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); cadence_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_cadence.id',ondelete='CASCADE')); ordem:Mapped[int]=mapped_column(Integer); dias_apos_inicio:Mapped[int]=mapped_column(Integer); tipo:Mapped[str]=mapped_column(String(40)); orientacao:Mapped[Optional[str]]=mapped_column(Text)
class ComercialLeadCadence(Base,TimestampMixin):
    __tablename__='comercial_lead_cadence'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); cadence_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_cadence.id',ondelete='CASCADE')); status:Mapped[str]=mapped_column(String(30),default='ativa'); iniciada_em:Mapped[datetime]=mapped_column(DateTime(timezone=True)); proximo_step_ordem:Mapped[int]=mapped_column(Integer,default=1); pausada_em:Mapped[Optional[datetime]]=mapped_column(DateTime(timezone=True))
class ComercialOpportunity(Base,TimestampMixin):
    __tablename__='comercial_opportunity'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); contato:Mapped[Optional[str]]=mapped_column(String(180)); dor_principal:Mapped[Optional[str]]=mapped_column(Text); solucao_provavel:Mapped[Optional[str]]=mapped_column(Text); servicos_relacionados:Mapped[list]=mapped_column(JSONB,default=list); valor_estimado:Mapped[Optional[float]]=mapped_column(Numeric(12,2)); probabilidade:Mapped[int]=mapped_column(Integer,default=0); etapa:Mapped[str]=mapped_column(String(60),default='oportunidade'); proxima_acao:Mapped[Optional[str]]=mapped_column(String(300)); data_prevista:Mapped[Optional[date]]=mapped_column(Date); responsavel_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL'))
class ComercialAIGeneration(Base):
    __tablename__='comercial_ai_generation'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[int]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); usuario_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL')); tipo:Mapped[str]=mapped_column(String(60)); modelo:Mapped[str]=mapped_column(String(80)); prompt_version:Mapped[str]=mapped_column(String(40)); entrada:Mapped[dict]=mapped_column(JSONB); resultado:Mapped[dict]=mapped_column(JSONB); tokens_entrada:Mapped[Optional[int]]=mapped_column(Integer); tokens_saida:Mapped[Optional[int]]=mapped_column(Integer); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ComercialSuppression(Base):
    __tablename__='comercial_suppression'; id:Mapped[int]=mapped_column(BigInteger,primary_key=True); lead_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('comercial_lead.id',ondelete='CASCADE')); tipo:Mapped[str]=mapped_column(String(30)); valor:Mapped[str]=mapped_column(String(300)); motivo:Mapped[Optional[str]]=mapped_column(Text); created_by_envoxer_id:Mapped[Optional[int]]=mapped_column(BigInteger,ForeignKey('envoxer.id',ondelete='SET NULL')); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
