server {
    listen 80;
    listen [::]:80;
    server_name cliente.envox.com.br;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name cliente.envox.com.br;

    ssl_certificate /etc/letsencrypt/live/cliente.envox.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cliente.envox.com.br/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        return 404;
    }
}
