"""Módulo Comercial — CRM inteligente de prospecção Envox Restaurantes.
Revision ID: 0036_comercial_prospect | Revises: 0035_f4_clima | 2026-09-02
"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB
revision: str = "0036_comercial_prospect"
down_revision: Union[str, None] = "0035_f4_clima"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table("comercial_pipeline_stage", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("codigo",sa.String(50),nullable=False,unique=True), sa.Column("nome",sa.String(100),nullable=False), sa.Column("ordem",sa.Integer(),nullable=False,server_default="0"), sa.Column("ativo",sa.Boolean(),nullable=False,server_default=sa.true()), sa.Column("tipo",sa.String(30),nullable=False,server_default="aberto"))
    op.create_table("comercial_lead", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("data_entrada",sa.Date(),server_default=sa.func.current_date(),nullable=False), sa.Column("nome_estabelecimento",sa.String(180),nullable=False), sa.Column("nome_fantasia",sa.String(180)), sa.Column("segmento",sa.String(80)), sa.Column("subsegmento",sa.String(80)), sa.Column("cidade",sa.String(100)), sa.Column("estado",sa.String(40)), sa.Column("bairro",sa.String(100)), sa.Column("telefone",sa.String(40)), sa.Column("whatsapp",sa.String(40)), sa.Column("email",sa.String(180)), sa.Column("origem",sa.String(80)), sa.Column("status_codigo",sa.String(50),nullable=False,server_default="novo"), sa.Column("responsavel_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("observacoes",sa.Text()), sa.Column("fit_score",sa.Integer(),nullable=False,server_default="0"), sa.Column("opportunity_score",sa.Integer(),nullable=False,server_default="0"), sa.Column("engagement_score",sa.Integer(),nullable=False,server_default="0"), sa.Column("score_total",sa.Integer(),nullable=False,server_default="0"), sa.Column("temperatura",sa.String(20),nullable=False,server_default="frio"), sa.Column("ultimo_contato_em",sa.DateTime(timezone=True)), sa.Column("proxima_acao",sa.String(300)), sa.Column("proxima_acao_em",sa.DateTime(timezone=True)), sa.Column("nao_prospectar",sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column("tenant_id",sa.BigInteger(),server_default="1"), sa.Column("deleted_at",sa.DateTime(timezone=True)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_index("ix_comercial_lead_status","comercial_lead",["status_codigo"]); op.create_index("ix_comercial_lead_responsavel","comercial_lead",["responsavel_envoxer_id"]); op.create_index("ix_comercial_lead_proxima_acao","comercial_lead",["proxima_acao_em"])
    op.create_table("comercial_lead_contact", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("nome",sa.String(160),nullable=False), sa.Column("cargo",sa.String(100)), sa.Column("telefone",sa.String(40)), sa.Column("whatsapp",sa.String(40)), sa.Column("email",sa.String(180)), sa.Column("principal",sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_lead_channel", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("tipo",sa.String(40),nullable=False), sa.Column("valor",sa.String(1000),nullable=False), sa.Column("ativo",sa.Boolean(),nullable=False,server_default=sa.true()), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.UniqueConstraint("lead_id","tipo",name="uq_comercial_lead_channel_tipo"))
    op.create_table("comercial_audit", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("executado_por_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("resumo",sa.Text()), sa.Column("tese_central",sa.Text()), sa.Column("forcas",JSONB,nullable=False,server_default="[]"), sa.Column("vazamentos",JSONB,nullable=False,server_default="[]"), sa.Column("oportunidades",JSONB,nullable=False,server_default="[]"), sa.Column("prioridade",sa.String(80)), sa.Column("risco_comercial",sa.String(80)), sa.Column("observacoes",JSONB,nullable=False,server_default="[]"), sa.Column("modelo",sa.String(80)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_audit_source", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("audit_id",sa.BigInteger(),sa.ForeignKey("comercial_audit.id",ondelete="SET NULL")), sa.Column("tipo",sa.String(50),nullable=False), sa.Column("fonte",sa.String(120)), sa.Column("url",sa.String(1200)), sa.Column("evidencia",sa.Text(),nullable=False), sa.Column("consultado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_insight", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("audit_id",sa.BigInteger(),sa.ForeignKey("comercial_audit.id",ondelete="CASCADE")), sa.Column("categoria",sa.String(50)), sa.Column("titulo",sa.String(220),nullable=False), sa.Column("evidencia",sa.Text(),nullable=False), sa.Column("impacto",sa.Text(),nullable=False), sa.Column("fonte",sa.String(400)), sa.Column("grau_confianca",sa.String(30),nullable=False,server_default="medio"), sa.Column("utilizado",sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column("utilizado_em",sa.DateTime(timezone=True)), sa.Column("ativo",sa.Boolean(),nullable=False,server_default=sa.true()), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index("ix_comercial_insight_utilizado","comercial_insight",["lead_id","utilizado"])
    op.create_table("comercial_message", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("direcao",sa.String(20),nullable=False), sa.Column("canal",sa.String(30),nullable=False), sa.Column("tipo",sa.String(40),nullable=False), sa.Column("conteudo",sa.Text(),nullable=False), sa.Column("responsavel_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("insight_id",sa.BigInteger(),sa.ForeignKey("comercial_insight.id",ondelete="SET NULL")), sa.Column("status_antes",sa.String(50)), sa.Column("status_depois",sa.String(50)), sa.Column("enviado_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("metadados",JSONB), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index("ix_comercial_message_lead","comercial_message",["lead_id","enviado_em"])
    op.create_table("comercial_activity", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("usuario_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("tipo",sa.String(60),nullable=False), sa.Column("descricao",sa.Text(),nullable=False), sa.Column("dados",JSONB), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index("ix_comercial_activity_lead","comercial_activity",["lead_id","created_at"])
    op.create_table("comercial_task", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("titulo",sa.String(220),nullable=False), sa.Column("descricao",sa.Text()), sa.Column("responsavel_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("prazo",sa.DateTime(timezone=True)), sa.Column("status",sa.String(30),nullable=False,server_default="pendente"), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_cadence", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("nome",sa.String(160),nullable=False), sa.Column("descricao",sa.Text()), sa.Column("ativa",sa.Boolean(),nullable=False,server_default=sa.true()), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_cadence_step", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("cadence_id",sa.BigInteger(),sa.ForeignKey("comercial_cadence.id",ondelete="CASCADE"),nullable=False), sa.Column("ordem",sa.Integer(),nullable=False), sa.Column("dias_apos_inicio",sa.Integer(),nullable=False), sa.Column("tipo",sa.String(40),nullable=False), sa.Column("orientacao",sa.Text()), sa.UniqueConstraint("cadence_id","ordem",name="uq_comercial_cadence_step_ordem"))
    op.create_table("comercial_lead_cadence", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("cadence_id",sa.BigInteger(),sa.ForeignKey("comercial_cadence.id",ondelete="CASCADE"),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="ativa"), sa.Column("iniciada_em",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("proximo_step_ordem",sa.Integer(),nullable=False,server_default="1"), sa.Column("pausada_em",sa.DateTime(timezone=True)), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_opportunity", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("contato",sa.String(180)), sa.Column("dor_principal",sa.Text()), sa.Column("solucao_provavel",sa.Text()), sa.Column("servicos_relacionados",JSONB,nullable=False,server_default="[]"), sa.Column("valor_estimado",sa.Numeric(12,2)), sa.Column("probabilidade",sa.Integer(),nullable=False,server_default="0"), sa.Column("etapa",sa.String(60),nullable=False,server_default="oportunidade"), sa.Column("proxima_acao",sa.String(300)), sa.Column("data_prevista",sa.Date()), sa.Column("responsavel_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_ai_generation", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),nullable=False), sa.Column("usuario_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("tipo",sa.String(60),nullable=False), sa.Column("modelo",sa.String(80),nullable=False), sa.Column("prompt_version",sa.String(40),nullable=False), sa.Column("entrada",JSONB,nullable=False), sa.Column("resultado",JSONB,nullable=False), sa.Column("tokens_entrada",sa.Integer()), sa.Column("tokens_saida",sa.Integer()), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_table("comercial_suppression", sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True), sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE")), sa.Column("tipo",sa.String(30),nullable=False), sa.Column("valor",sa.String(300),nullable=False), sa.Column("motivo",sa.Text()), sa.Column("created_by_envoxer_id",sa.BigInteger(),sa.ForeignKey("envoxer.id",ondelete="SET NULL")), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False), sa.UniqueConstraint("tipo","valor",name="uq_comercial_suppression_tipo_valor"))
    op.create_table("comercial_tag",sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column("nome",sa.String(80),nullable=False,unique=True)); op.create_table("comercial_lead_tag",sa.Column("lead_id",sa.BigInteger(),sa.ForeignKey("comercial_lead.id",ondelete="CASCADE"),primary_key=True),sa.Column("tag_id",sa.BigInteger(),sa.ForeignKey("comercial_tag.id",ondelete="CASCADE"),primary_key=True))
    stages=[("novo","Novo",10,"aberto"),("a_pesquisar","A pesquisar",20,"aberto"),("em_analise","Em análise",30,"aberto"),("analise_concluida","Análise concluída",40,"aberto"),("pronto_abordagem","Pronto para abordagem",50,"aberto"),("mensagem_1_enviada","Mensagem 1 enviada",60,"contato"),("respondeu","Respondeu",70,"contato"),("em_conversa","Em conversa",80,"contato"),("follow_up_1","Follow-up 1",90,"contato"),("follow_up_2","Follow-up 2",100,"contato"),("follow_up_3","Follow-up 3",110,"contato"),("oportunidade","Oportunidade",120,"oportunidade"),("reuniao_agendada","Reunião agendada",130,"oportunidade"),("proposta","Proposta",140,"oportunidade"),("negociacao","Negociação",150,"oportunidade"),("ganho","Ganho",160,"fechado"),("perdido","Perdido",170,"fechado"),("sem_resposta","Sem resposta",180,"fechado"),("pausado","Pausado",190,"fechado"),("nao_prospectar","Não prospectar",200,"fechado")]
    t=sa.table("comercial_pipeline_stage",sa.column("codigo",sa.String),sa.column("nome",sa.String),sa.column("ordem",sa.Integer),sa.column("tipo",sa.String)); op.bulk_insert(t,[{"codigo":c,"nome":n,"ordem":o,"tipo":tp} for c,n,o,tp in stages])
    c=sa.table("comercial_cadence",sa.column("id",sa.BigInteger),sa.column("nome",sa.String),sa.column("descricao",sa.Text),sa.column("ativa",sa.Boolean)); op.bulk_insert(c,[{"id":1,"nome":"Prospecção Restaurantes · Padrão","descricao":"D0, D2, D5, D10 e D20. Cada contato precisa de uma nova razão para existir.","ativa":True}])
    s=sa.table("comercial_cadence_step",sa.column("cadence_id",sa.BigInteger),sa.column("ordem",sa.Integer),sa.column("dias_apos_inicio",sa.Integer),sa.column("tipo",sa.String),sa.column("orientacao",sa.Text)); op.bulk_insert(s,[{"cadence_id":1,"ordem":1,"dias_apos_inicio":0,"tipo":"abordagem","orientacao":"Mensagem inicial com primeiro ouro."},{"cadence_id":1,"ordem":2,"dias_apos_inicio":2,"tipo":"follow_up","orientacao":"Novo ouro ou evidência; não apenas 'viu minha mensagem?'."},{"cadence_id":1,"ordem":3,"dias_apos_inicio":5,"tipo":"follow_up","orientacao":"Nova oportunidade contextual."},{"cadence_id":1,"ordem":4,"dias_apos_inicio":10,"tipo":"follow_up","orientacao":"Nova razão comercial, sem pressão artificial."},{"cadence_id":1,"ordem":5,"dias_apos_inicio":20,"tipo":"reativacao","orientacao":"Reativação com contexto novo."}])

def downgrade() -> None:
    for table in ["comercial_lead_tag","comercial_tag","comercial_suppression","comercial_ai_generation","comercial_opportunity","comercial_lead_cadence","comercial_cadence_step","comercial_cadence","comercial_task","comercial_activity","comercial_message","comercial_insight","comercial_audit_source","comercial_audit","comercial_lead_channel","comercial_lead_contact","comercial_lead","comercial_pipeline_stage"]: op.drop_table(table)
